name:                iapplicative-builder
version:             0.1.0.0
github:              "githubuser/cached-builder"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cached-builder#readme>

dependencies:
- base >= 4.7 && < 5
- indexed

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
  - algebraic-graphs
  - bifunctors
  - containers
  - deepseq
  - dlist
  - free
  - hashable
  - kan-extensions
  - monad-par
  - parallel
  - tagged
  - unordered-containers

executables:
  iapplicative-builder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iapplicative-builder

tests:
  iapplicative-builder-test:
    main: test.hs
    source-dirs: tests
    build-tools:
    - tasty-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - iapplicative-builder
    - tasty
    - tasty-hunit
    - inspection-testing